# Generated by Django 5.1 on 2024-09-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polygon',
            options={'verbose_name': 'Список полигонов', 'verbose_name_plural': 'Список полигонов'},
        ),
    ]
